name: Compile and Upload IPK Package

on:
  push:
    branches:
      - main  # 或者你的主要分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenWRT SDK environment
      run: |
        # Download and extract OpenWRT SDK (replace with your SDK URL)
        SDK_URL=https://downloads.openwrt.org/releases/22.03.5/targets/x86/generic/openwrt-sdk-22.03.5-x86-generic_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        curl -L $SDK_URL | tar xJ

        # Set up environment for OpenWRT SDK
        export PATH=$PATH:$PWD/staging_dir/host/bin
        export STAGING_DIR=$PWD/staging_dir

    - name: Clone IPK repository
      run: |
        git clone --depth 1 https://github.com/Lienol/openwrt-OpenAppFilter.git ipk-package

    - name: Build IPK package
      run: |
        # Change to your IPK package directory
        cd ipk-package

        # Run the compile command (adjust as needed)
        make package/luci-app-oaf/compile V=99

    - name: Upload IPK files
      uses: actions/upload-artifact@v2
      with:
        name: ipk-packages
        path: ipk-package/bin/packages
