name: Compile and Upload IPK Package

on:
  push:
    branches:
      - main  # 或者你的主要分支名称
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: 8632.config
  OS_ARCH: X86_32
  DIY_P1_SH: diy.sh
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Clone IPK repository
      run: |
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

  

    - name: Upload IPK files
      uses: actions/upload-artifact@v2
      with:
        name: ipk-packages
        path: openwrt/bin/targets/x86/packages
